### PR TITLE
Initial setup for notebook.

### PR DESCRIPTION
**Pull request by jbkalmbach**

### CODE REVIEW

**Comment by jbkalmbach** [comment]
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213714'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>It's just a matter of the specific perturbations affecting the inside border of the intra-focal image and related to the need for dilation in this particular set up of the optical state.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213784'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>Yes, it's the same initial optical state as in the corner wavefront sensor example above so we get the same intra-focal effect. I've add a line into the caption to explain this.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213858'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>Ok, OPD line thickness changed and moved to use opd-fit as above and added a dashed line at 0.0 to guide eye as suggested.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213897'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>Ok, rephrased the first sentence.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213922'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>Here you are talking about the offset in extra and intra-focal overlap that was explained below and should be moved up right? Because yes, in a non-perturbed optical system this overlap should be identical.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213875'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jbkalmbach** [comment]
<p>Do the images included below answer this? Should they be moved up here?</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213838'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>Yes, the second image below that shows that the sources are rotated by 180 degrees when using the piston, it would be good to have it here </p><p> </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213838'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>Yes, about the very first image above for comCam, where the intra-focal had a different amount of overlap than the extra-focal . It would be worth clarifying that indeed due to symmetry in the absence of additional perturbations we would expect that overlapping region to be identical.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213875'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>That illustration could be closer to that first comCam image as it explains what we're looking at and how it's different from the CWFS case</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/pull/1/discussion/#comment-2159213875'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by suberlak — APPROVED** [review]
Looked at all changes in https://app.reviewnb.com/lsst-sitcom/sitcomtn-130/commit/3563aec393b8196e33f509bd0b54abc10902dc34/ ,  looks good!

**Pull request merged**
